# Generated by Django 3.1.4 on 2021-05-17 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='nmae',
            new_name='name',
        ),
    ]
